import react from '@vitejs/plugin-react';
import { defineConfig, type HtmlTagDescriptor, type Plugin } from 'vite';
import { wedding } from './src/config/wedding.ts';
import { formatCardDate } from './src/lib/date.ts';

/** Share image and icon, generated by `pnpm share-images` (scripts/share-images.mjs). */
const SHARE_IMAGE = { path: '/og-image.jpg', width: '1200', height: '630' };
const TOUCH_ICON = '/apple-touch-icon.png';

/** Injects page metadata from the wedding config so link previews (WhatsApp, iMessage…) match the content. */
function invitationMeta(): Plugin {
  const { groom, bride, date, venue } = wedding;
  const title = `${groom.name} with ${bride.name} · Wedding Invitation`;
  const { description, themeColor, siteUrl } = wedding.meta;
  // Most link previewers only fetch absolute image URLs.
  const base = siteUrl?.replace(/\/$/, '') ?? '';
  const image = `${base}${SHARE_IMAGE.path}`;
  const imageAlt = `A sealed envelope tied with a satin ribbon: ${groom.name} with ${bride.name}, ${formatCardDate(date)}, ${venue.name}`;

  const meta = (attrs: Record<string, string>): HtmlTagDescriptor => ({ tag: 'meta', attrs, injectTo: 'head' });

  return {
    name: 'invitation-meta',
    configResolved(config) {
      if (config.command === 'build' && !base) {
        config.logger.warn('\n[invitation-meta] wedding.meta.siteUrl is not set, so og:image is relative and some apps won’t show the preview.');
      }
    },
    transformIndexHtml: () => [
      { tag: 'title', children: title, injectTo: 'head' },
      meta({ name: 'description', content: description }),
      meta({ name: 'theme-color', content: themeColor }),
      { tag: 'link', attrs: { rel: 'apple-touch-icon', href: TOUCH_ICON }, injectTo: 'head' },
      meta({ property: 'og:type', content: 'website' }),
      meta({ property: 'og:title', content: title }),
      meta({ property: 'og:description', content: description }),
      ...(base ? [meta({ property: 'og:url', content: `${base}/` })] : []),
      meta({ property: 'og:image', content: image }),
      meta({ property: 'og:image:width', content: SHARE_IMAGE.width }),
      meta({ property: 'og:image:height', content: SHARE_IMAGE.height }),
      meta({ property: 'og:image:alt', content: imageAlt }),
      meta({ name: 'twitter:card', content: 'summary_large_image' }),
      meta({ name: 'twitter:image', content: image }),
    ],
  };
}

export default defineConfig({
  plugins: [react(), invitationMeta()],
});
